"""
round2_engine.py
──────────────────
Round 2 = Project & Experience Deep Dive. Fully dynamic, generated by
Gemini from the candidate's own parsed projects + experience entries —
no question bank involved. This round is only offered at the
employer's manual discretion after reviewing the Round 1 report (per
spec: the system never auto-advances a candidate into Round 2).
"""

import gemini_client

QUESTION_COUNT = 4


def generate_round2_questions(projects, experience):
    """Cross-references projects and job history to ask about how the
    candidate actually handled real work — not hypotheticals."""
    context_bits = []
    for p in (projects or [])[:3]:
        context_bits.append(f"Project: {p.get('name','')} — {p.get('description','')} (tech: {', '.join(p.get('technologies', []))})")
    for e in (experience or [])[:3]:
        resp = "; ".join(e.get("responsibilities", [])[:3])
        context_bits.append(f"Role: {e.get('role','')} ({e.get('duration','')}) — {resp}")

    context = "\n".join(context_bits) or "No detailed project/experience data was extracted from the resume."

    prompt = f"""You are a senior technical interviewer conducting a deep-dive
round on a candidate's real project and work experience (extracted below).
Generate {QUESTION_COUNT} distinct, specific interview questions that probe
HOW they actually handled things — architecture decisions, trade-offs,
failures, ownership, scale/complexity — not generic behavioral questions.

CANDIDATE'S PROJECTS AND EXPERIENCE:
{context}

Return ONLY valid JSON, no markdown fences, as a list:
[{{"question": "...", "model_answer": "brief ideal-answer outline",
   "rubric": ["criterion1", "criterion2", "criterion3"], "topic": "short label"}}]
"""
    result = gemini_client._call_gemini_json(prompt)
    if not result or not isinstance(result, list) or not result:
        return [{
            "question": "Walk me through the most technically challenging piece of work on your resume — what made it hard, and how did you approach it?",
            "model_answer": "",
            "rubric": ["Specific technical challenge", "Clear reasoning", "Ownership of the outcome"],
            "topic": "General",
        }]
    cleaned = []
    for q in result[:QUESTION_COUNT]:
        if isinstance(q, dict) and "question" in q:
            q.setdefault("model_answer", "")
            q.setdefault("rubric", [])
            q.setdefault("topic", "")
            cleaned.append(q)
    return cleaned or [{
        "question": "Walk me through the most technically challenging piece of work on your resume — what made it hard, and how did you approach it?",
        "model_answer": "", "rubric": [], "topic": "General",
    }]


def grade_round2(question, rubric, model_answer, candidate_answer):
    """Returns (score_0_to_10, justification)."""
    result = gemini_client.grade_answer(question, rubric, model_answer, candidate_answer)
    return result["score"], result.get("justification", "")


def score_round2(gemini_scores):
    if not gemini_scores:
        return 0.0
    avg = sum(gemini_scores) / len(gemini_scores)
    return round((avg / 10) * 100, 1)
