"""
round3_engine.py
──────────────────
Round 3 = JD-Fit Testing. Fully dynamic, generated by Gemini directly
from the job description text plus the candidate's experience — tests
whether the candidate can operate at what THIS specific job actually
requires (not generic skill trivia, that's Round 1's job).
"""

import gemini_client

QUESTION_COUNT = 3


def generate_round3_questions(jd_text, experience_yrs, skills):
    prompt = f"""You are evaluating whether a candidate is truly ready for a
specific job, based on its job description. Generate {QUESTION_COUNT}
scenario-style questions grounded in what THIS job description actually
asks for (responsibilities, scale, seniority expectations) — testing
whether the candidate can operate at that level, not generic knowledge.

JOB DESCRIPTION:
\"\"\"
{jd_text or '(no description provided)'}
\"\"\"

Candidate's claimed experience: {experience_yrs} years
Candidate's claimed skills: {', '.join(skills or [])}

Return ONLY valid JSON, no markdown fences, as a list:
[{{"question": "...", "model_answer": "brief ideal-answer outline",
   "rubric": ["criterion1", "criterion2", "criterion3"]}}]
"""
    result = gemini_client._call_gemini_json(prompt)
    if not result or not isinstance(result, list) or not result:
        return [{
            "question": "Based on this role's responsibilities, describe how you'd approach your first 30 days and what you'd prioritize.",
            "model_answer": "", "rubric": ["Relevant prioritization", "Realistic scope", "Awareness of role expectations"],
        }]
    cleaned = []
    for q in result[:QUESTION_COUNT]:
        if isinstance(q, dict) and "question" in q:
            q.setdefault("model_answer", "")
            q.setdefault("rubric", [])
            cleaned.append(q)
    return cleaned or [{
        "question": "Based on this role's responsibilities, describe how you'd approach your first 30 days and what you'd prioritize.",
        "model_answer": "", "rubric": [],
    }]


def grade_round3(question, rubric, model_answer, candidate_answer):
    """Returns (score_0_to_10, justification)."""
    result = gemini_client.grade_answer(question, rubric, model_answer, candidate_answer)
    return result["score"], result.get("justification", "")


def score_round3(gemini_scores):
    if not gemini_scores:
        return 0.0
    avg = sum(gemini_scores) / len(gemini_scores)
    return round((avg / 10) * 100, 1)
